[test_framework]
log_dir = "./logs"

[board]
board_name = "milkv_duo_s"

[serial]
serial_file = "/dev/ttyUSB0"
bund_rate = 115200
serial_name = "sdwirec_alpha"
sd_mux_device = "/dev/sda"

[os_list]
[os_list.Debian]
url = "/home/aisuneko/duos_sd.img"
dd_params = ["bs=4M", "status=progress"]
test_config = "./tests/debian_test.toml"
auto_login = true
username = "root"
password = "rv"
login_prompts = ["duos login:", "Username:"]
password_prompts = ["Password:", "Secret:"]
shell_prompt = "root@duos:~#"
