[test_framework]
log_dir = "./logs"

[board]
board_name = "visionfive"

[serial]
serial_file = "/dev/ttyUSB0"
bund_rate = 115200
serial_name = "sdwirec_alpha"
sd_mux_device = "/dev/sda"

[os_list]
[os_list.openEuler]
url = "/home/xyz/.local/share/ruyi/blobs/oerv-starfive-visionfive-base-0
.2309.1/openEuler-23.09-V1-base-visionfive-preview.img"
dd_params = ["bs=4M", "conv=fsync", "status=progress"]
test_config = "./tests/openeuler_test.toml"
